apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
        app: employee-service-label
    spec:
      containers:
      - name: employee-service-name
        image: spring-employee-service:0.0.1
        imagePullPolicy: Never
        ports:
          - containerPort: 8060