kind: Service
apiVersion: v1
metadata:
  name: payroll-service
spec:
  selector:
    app: payroll-service-label
  type: ClusterIP 
  ports:
  - name: payroll-service-port
    port: 8050
    targetPort: 8050