zuul:
  routes:
    payroll-service:
      path: /payroll/**
      serviceId: payroll-service
    employee-service:
      path: /employee/**
      serviceId: employee-service
      
server:
  port: 8070
  
ribbon:
  eureka:
    enabled: false

payroll-service:
  ribbon:
    listOfServers: ${payrollServiceName}

employee-service:
  ribbon:
    listOfServers: ${employeeServiceName}
    