zuul:
  routes:
    employee-service:
      path: /employee/**
      serviceId: employee-service
server:
  port: 8070
  
ribbon:
  eureka:
    enabled: false

employee-service:
  ribbon:
    listOfServers: ${employeeServiceName}